# Generated by Django 3.2.13 on 2022-05-30 22:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascotas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mascota',
            name='fecha_nacimiento',
        ),
        migrations.AddField(
            model_name='mascota',
            name='edad',
            field=models.IntegerField(null=True, validators=[django.core.validators.MaxValueValidator(2)]),
        ),
    ]
