# Generated by Django 3.2.13 on 2022-05-30 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('marca', models.CharField(max_length=100)),
                ('ano_creacion', models.IntegerField(max_length=4)),
                ('cap_lts', models.FloatField(default=0.0)),
            ],
        ),
    ]
