# Generated by Django 3.2.13 on 2022-05-30 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carros', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carro',
            name='ano_creacion',
            field=models.IntegerField(),
        ),
    ]
